backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
show_preview_links: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} - {{commit_date}}"
    sortableFields: ['commit_date', 'title']
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string", default: "New Blog Post", hint: "Replace with a real title in title case."}
      - {label: "Description", name: "description", widget: "text", required: false, hint: "Please fill in for SEO reasons"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", default: false}
      - {label: "Featured Image", name: "featuredimage", widget: image, default: "/img/featured_placeholder.png", hint: "Please change the placeholder image."}
      - {label: "Featured Image Title", name: "featuredimageTitle", widget: string, required: false, hint: "Please remember to fill it in for accessibility and SEO. Make it different then alt."}
      - {label: "Featured Image Alt", name: "featuredimageAlt", widget: string, required: false, hint: "Please remember to fill it in for accessibility and SEO. Make it different then title."}
      - {label: "Promo Image", name: "promoimage", widget: image, default: "/img/promo_placeholder.png", hint: "Please change the placeholder image."}
      - {label: "Promo Image Title", name: "promoimageTitle", widget: string, required: false, hint: "Please remember to fill it in for accessibility and SEO. Make it different then alt."}
      - {label: "Promo Image Alt", name: "promoimageAlt", widget: string, required: false, hint: "Please remember to fill it in for accessibility and SEO. Make it different then title."}
      - {label: "Promo Image Author", name: "promoimageAuthor", widget: string, required: false}
      - {label: "Promo Image Url", name: "promoimageUrl", widget: string, required: false}
      - {label: "Card Image", name: "cardimage", widget: image, default: "/img/card_placeholder.png", hint: "Please change the placeholder image."}
      - {label: "Card Image Title", name: "cardimageTitle", widget: string, required: false, hint: "Please remember to fill it in for accessibility and SEO. Make it different then alt."}
      - {label: "Card Image Alt", name: "cardimageAlt", widget: string, required: false, hint: "Please remember to fill it in for accessibility and SEO. Make it different then title."}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["Stretches"], hint: "Don't add too many and seek consistency with other blogposts"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: ImageTitle, name: imageTitle, widget: string}
          - {label: ImageAlt, name: imageAlt, widget: string}
          - {label: Subheading, name: subheading, widget: text}
          - {label: Prosection, name: prosection, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: Image, name: image, widget: image},
              {label: ImageTitle, name: imageTitle, widget: string},
              {label: ImageAlt, name: imageAlt, widget: string},
              {label: painAddition, name: painAddition, widget: list, fields: [
                {label: Pain, name: pain, widget: string}
                ]
              }
              ]}
          - {label: Comingsoon, name: comingsoon, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Image, name: image, widget: image}, 
            {label: ImageTitle, name: imageTitle, widget: string}, 
            {label: ImageAlt, name: imageAlt, widget: string}, 
            {label: Description, name: description, widget: text}]}
          - {label: Everything, name: everything, widget: object, fields: [
              {label: List, name: list, widget: list, fields: [
                {label: Feature, name: feature, widget: object, fields: [
                  {label: Title, name: title, widget: string},
                  {label: Image, name: image, widget: image}, 
                  {label: ImageTitle, name: imageTitle, widget: string},
                  {label: ImageAlt, name: imageAlt, widget: string},
                  {label: description, name: description, widget: text}
                ]}
              ]}
            ]}
          - {label: CreatedBy, name: createdBy, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Image, name: image, widget: image}, 
            {label: ImageTitle, name: imageTitle, widget: string},
            {label: ImageAlt, name: imageAlt, widget: string}, 
            {label: description, name: description, widget: text}]}
          - {label: NewLifeGrid, name: newLifeGrid, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Description, name: description, widget: string},
            {label: List, name: list, widget: list, fields: [
              {label: Item, name: item, widget: object, fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: text}, 
                {label: Image, name: image, widget: image},
                {label: ImageTitle, name: imageTitle, widget: string},
                {label: ImageAlt, name: imageAlt, widget: string},
                ]
              }, 
              ]} 
            ]}
          - {label: Steps, name: steps, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: List, name: list, widget: list, fields: [
              {label: Item, name: item, widget: object, fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: text}, 
                ]
              }, 
              ]} 
            ]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Header1", name: "header1", widget: "string"}
          - {label: "Header2", name: "header2", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "ImageAlt", name: "imageAlt", widget: "string"}
          - {label: "ImageTitle", name: "imageTitle", widget: "string"}
          - {label: "Mission", name: "mission", widget: "object", fields: [
            {label: "title", name: "title", widget: "string"},
            {label: "missionStatement", name: "missionStatement", widget: "string" },
            {label: "description1", name: "description1", widget: "text"},
            {label: "description2", name: "description2", widget: "text"}
          ]}
          - {label: "aboutEmilia", name: "aboutEmilia", widget: "object", fields: [
            {label: "image", name: "image", widget: "image"},
            {label: "ImageAlt", name: "imageAlt", widget: "string"},
            {label: "ImageTitle", name: "imageTitle", widget: "string"},
            {label: "title", name: "title", widget: "string"},
            {label: "description1", name: "description1", widget: "text"},
            {label: "description2", name: "description2", widget: "text"},
            {label: "description3", name: "description3", widget: "text"},
          ]}
          - {label: "familyBusiness", name: "familyBusiness", widget: "object", fields: [
            {label: "image", name: "image", widget: "image"},
            {label: "ImageAlt", name: "imageAlt", widget: "string"},
            {label: "ImageTitle", name: "imageTitle", widget: "string"},
            {label: "title", name: "title", widget: "string"},
            {label: "description1", name: "description1", widget: "text"},
            {label: "description2", name: "description2", widget: "text"},
          ]}
          - {label: Comingsoon, name: comingsoon, widget: object, fields: [{label: Title, name: title, widget: string},{label: Image, name: image, widget: image}, {label: "ImageAlt", name: "imageAlt", widget: "string"},
            {label: "ImageTitle", name: "imageTitle", widget: "string"},{label: Description, name: description, widget: text}]}